services:
  api:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      UV_THREADPOOL_SIZE: 128
      NODE_ENV: production
      LOG_LEVEL: info
      PORT: 3000
      PG_CONNECTION: postgres://root-user:password123!@db:5432/dev
    command: ['npm', 'run', 'start:dev']
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root-user
      POSTGRES_PASSWORD: password123!
      PGPASSWORD: password123!
    healthcheck:
      test: ['CMD', '/health-check.sh', 'postgres', 'root-user', 'password123!']
      interval: 15s
      timeout: 10s
      retries: 20
    ports:
      - '15432:5432'
    tty: true
    volumes:
      - ./db/health-check.sh:/health-check.sh
      - ./db/postgresql.conf:/etc/postgresql.conf
    tmpfs:
      - /var/lib/postgresql/data
